// src/routes/components/footer.svelte
<script>
    import Home from "../index.svelte";
   
   </script>
   <body>
   <div class="inset-x-0 bottom-0 z-40 fixed">
   <div class="flex w-full cursor-pointer shadow-xl backdrop-blur-lg  outline-none focus:outline-none ease-linear transition-all duration-150 justify-center items-center py-3">
        <h1 class="text-font text-sm font-bold cursor-pointer text-shadow-xl">This Site Made By <a href="https://github.com/xDarkShiny" target="_blank" class="text-red-500">DarkShiny</a>. | <a class="text-green-500" href="https://stats.uptimerobot.com/kOjwrukvZr">Status</a></h1>
     </div>
   </div>
   </body>

// src/layout/companents/footer.jsx
function footer() {
    return (
        <div className="w-full h-10 flex items-center justify-center bg-[#232323]">
                <a target="_blank" href="https://github.com/xDarkShiny/darkshiny.me" className="text-white/70">The <span className="bg-[#006bff] rounded-full px-2 py-0.5 text-white">source code</span> for this site is here.</a>
        </div>
    )
}

export default footer;
